// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'element-separator': string;
  'modifier-separator': string;
  'namespace': string;
  'state-prefix': string;
}
export const cssExports: CssExports;
export default cssExports;
